services: 
  postgres:
    image: postgres:latest
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:postgres@postgres:5433/mydb
    command: ["npm", "run", "start:prod"]

volumes:
  pgdata: